apiVersion: apps/v1
kind: Deployment
metadata:
  name: just-apps
  namespace: app-store
  labels:
    app: just-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: just-apps
  template:
    metadata:
      labels:
        app: just-apps
    spec:
      containers:
        - name: app
          image: artifactory-jfrog.apps.ocp4.svc.prod.pl2cloud.de/custom-shared-images/jneubert/just-apps:1.0.0
          ports:
            - containerPort: 3000
          env:
            - name: APP_CONFIG_PATH
              value: "/app/config/config.yaml"
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: app-config
