---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: app-store-route
  namespace: app-store
spec:
  to:
    kind: Service
    name: plain-app-store
  port:
    targetPort: http
  tls:
    termination: edge

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: app-store-route-ndbvn
  namespace: app-store
  labels:
    type: ndbvn
  annotations:
    route.openshift.io/termination: edge
spec:
  ingressClassName: openshift-ndbvn
  rules:
    - host: app-store.aa.plain.doi-de.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: plain-app-store
                port:
                  name: http