apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app-store.fullname" . }}-backend-config
  labels:
    {{- include "app-store.labels" . | nindent 4 }}
data:
  config.yaml: |
    log_level: {{ .Values.config.logLevel }}
    port: 8082
    database:
      server: {{ .Values.config.database.server }}
      port: {{ .Values.config.database.port }}
      name: {{ .Values.config.database.name }}
      user: {{ .Values.config.database.user }}
      password: {{ .Values.config.database.password }}
    jwt:
      secret: {{ .Values.config.jwtSecret }}
    oidc:
      enabled: {{ .Values.config.oidc.enabled }}
      issuer: {{ .Values.config.oidc.issuer | quote }}
      client_id: {{ .Values.config.oidc.clientId | quote }}
      admin_group: {{ .Values.config.oidc.adminGroup | quote }}
