{{- if and .Values.secrets.create (not .Values.secrets.vault.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "just-apps.fullname" . }}-secrets
  labels:
    {{- include "just-apps.labels" . | nindent 4 }}
type: Opaque
data:
  database-password: {{ .Values.config.database.password | b64enc | quote }}
  jwt-secret: {{ .Values.config.jwtSecret | b64enc | quote }}
  oidc-client-secret: {{ .Values.config.oidc.clientSecret | b64enc | quote }}
  nextauth-secret: {{ .Values.frontend.env.authSecret | b64enc | quote }}
  postgresql-password: {{ .Values.postgresql.auth.password | b64enc | quote }}
{{- end }}
