{{- if and .Values.secrets.create .Values.secrets.vault.enabled }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "just-apps.fullname" . }}-vs-secrets
  labels:
    {{- include "just-apps.labels" . | nindent 4 }}
spec:
  vaultAuthRef: {{ .Values.secrets.vault.authRef }}
  type: {{ .Values.secrets.vault.type }}
  mount: {{ .Values.secrets.vault.mount }}
  namespace: {{ .Values.secrets.vault.namespace }}
  path: {{ .Values.secrets.vault.path }}
  refreshAfter: {{ .Values.secrets.vault.refreshAfter }}
  destination:
    create: {{ .Values.secrets.vault.destination.create }}
    name: {{ include "just-apps.fullname" . }}-secrets
{{- end }}