{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "marktplatz.fullname" . }}-postgresql
  labels:
    {{- include "marktplatz.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: {{ .Values.postgresql.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.postgresql.service.port | default 5432 }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "marktplatz.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
{{- end }}