# Default values for app-store.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# deploymentMode: "monolith" or "microservices"
deploymentMode: monolith

replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# Configuration for both modes
config:
  logLevel: info
  port: 8080
  database:
    # If using the internal postgresql (postgresql.enabled=true), the server should be:
    # <release-name>-app-store-postgresql
    server: app-store-postgresql
    port: 5432
    name: app_store
    user: postgres
    password: "LefqrWPauTW73v"
  jwtSecret: ".bxh'{cI9_X;~'Vp-G46vmmo6~MS7Q0G"
  oidc:
    enabled: true
    issuer: "https://login-keycloak.apps.ocp4.m017-1.ten.prod.pl2cloud.de/realms/m017-1"
    clientId: "app-store"
    clientSecret: "mQHBzEog8QxMeYv0blq2KsLGrLki6bqG"
    adminGroup: "App-Store-Admin"
    insecure: true
  cors:
    allowedOrigins:
      - "https://app-store.apps.ocp4.m017-1.ten.prod.pl2cloud.de"

# Monolith specific configuration (both frontend and backend in one container)
monolith:
  image:
    repository: artifactory-jfrog.apps.ocp4.svc.prod.pl2cloud.de/custom-shared-images/jneubert/plain-marktplatz
    pullPolicy: Always
    tag: "0.8.0"
  service:
    type: ClusterIP
    port: 80
    backendPort: 8080
    frontendPort: 3000
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

# Microservices specific configuration
backend:
  replicaCount: 1
  image:
    repository: artifactory-jfrog.apps.ocp4.svc.prod.pl2cloud.de/custom-shared-images/jneubert/plain-marktplatz-backend
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 8182 # External port for the service
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

frontend:
  replicaCount: 1
  image:
    repository: gartifactory-jfrog.apps.ocp4.svc.prod.pl2cloud.de/custom-shared-images/jneubert/plain-marktplatz-frontend
    pullPolicy: IfNotPresent
    tag: "latest"
  env:
    # URL of the backend API (internal or external)
    # Default assumes microservices mode with backend service name
    apiUrl: "https://app-store.apps.ocp4.m017-1.ten.prod.pl2cloud.de/api/v1"
    nextauthUrl: "https://app-store.apps.ocp4.m017-1.ten.prod.pl2cloud.de"
    authSecret: "VN4Omg9bPQ%T{+b2tTR28T-L*=Y0q<B{"
  service:
    type: ClusterIP
    port: 80
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

ingress:
  enabled: true
  className: ""
  annotations:
    route.openshift.io/termination: edge
  hosts:
    - host: app-store.apps.ocp4.m017-1.ten.prod.pl2cloud.de
      paths:
        - path: /
          pathType: Prefix
        - path: /api/v1
          pathType: Prefix
          port: 8080
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

postgresql:
  enabled: true
  image: 'artifactory-jfrog.apps.ocp4.svc.prod.pl2cloud.de/dhi-remote/postgres:17-alpine3.22'
  pullPolicy: IfNotPresent
  # Auf OpenShift ist es oft besser, einen anderen Pfad für die Daten zu nutzen.
  # Das offizielle Image hat unter /var/lib/postgresql oft Restriktionen.
  mountPath: /bitnami/postgresql/data
  persistence:
    enabled: true
    storageClassName: ocs-external-storagecluster-ceph-rbd
    size: 20Gi
  auth:
    database: "app_store"
    password: "LefqrWPauTW73v"
    username: "postgres"
  service:
    type: ClusterIP
    port: 5432
  # Auf OpenShift werden UIDs automatisch zugewiesen. 
  # Manuelle UIDs führen oft zu Permission-Problemen am Volume.
  podSecurityContext: {}
  securityContext: {}
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}
